[features]
seeds = false
skip-lint = false

[programs.localnet]
tornado_mixer = "31zAuv25vz5tV8oiHuq49Zd827mNpbaaZ6P7da6hHB8g"

[programs.devnet]
tornado_mixer = "31zAuv25vz5tV8oiHuq49Zd827mNpbaaZ6P7da6hHB8g"

[programs.mainnet]
tornado_mixer = "31zAuv25vz5tV8oiHuq49Zd827mNpbaaZ6P7da6hHB8g"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
