[workspace]
resolver = "2"

members = [
    "programs/*"
]
[workspace.dependencies]
anchor-lang = "0.29.0"


[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
