[features]
seeds = false
skip-lint = false

[programs.devnet]
tornado_solana = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"
program = "spl_account_compression.so"

[[test.genesis]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"
program = "spl_noop.so"

# Light Protocol Groth16 verifier program ID (placeholder)
[[test.genesis]]
address = "22222222222222222222222222222222"
program = "light_groth16_verifier.so"
